"""
Simple PDF report generator for Phase 4
"""

import os
from datetime import datetime

def generate_simple_report(incident_id: int, incident_data: dict, 
                          output_dir: str = "reports") -> str:
    """Generate a simple text report (can be upgraded to PDF later)"""
    
    os.makedirs(output_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"incident_{incident_id}_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)
    
    # Simple report content
    content = f"""========================================
SECURITY INCIDENT REPORT - PHASE 4
========================================

INCIDENT DETAILS:
-----------------
ID: #{incident_id}
Title: {incident_data.get('title', 'N/A')}
Severity: {incident_data.get('max_severity', 'N/A')}
Status: {incident_data.get('status', 'N/A')}
Start Time: {incident_data.get('start_ts_utc', 'N/A')}
Last Update: {incident_data.get('last_update_ts_utc', 'N/A')}

SUMMARY:
--------
{incident_data.get('summary', 'No summary available')}

OPERATIONAL RESPONSE:
---------------------
Report Generated: {datetime.now().isoformat()}
Generated By: Security Monitor System
Phase: 4 (Operational Response)

========================================
END OF REPORT
========================================
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return filepath