# reporting/pdf_generator.py (محدث)
import os
import sys
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors

class SimplePDFGenerator:
    """Simple PDF generator without font issues"""
    
    def generate(self, content: str, output_path: str) -> str:
        """Generate a simple PDF from text content"""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        
        # Use default font
        c.setFont("Helvetica", 10)
        
        # Split content into lines
        lines = content.split('\n')
        y_position = height - 50
        
        for line in lines:
            if y_position < 50:
                c.showPage()
                c.setFont("Helvetica", 10)
                y_position = height - 50
            
            # Draw line (limit to 100 characters)
            c.drawString(50, y_position, line[:100])
            y_position -= 15
        
        # Add footer
        c.setFont("Helvetica", 8)
        c.drawString(50, 30, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        c.drawString(50, 15, "Cybersecurity SOC Dashboard - Phase 4")
        
        c.save()
        return output_path
    
    def generate_incident_report(self, incident_data: dict, alerts: list = None, ai_summary: dict = None) -> str:
        """Generate incident report"""
        content = f"""
SECURITY INCIDENT REPORT
========================

Incident ID: {incident_data.get('id', 'N/A')}
Title: {incident_data.get('title', 'No title')}
Severity: {incident_data.get('max_severity', 'N/A')}
Status: {incident_data.get('status', 'N/A')}
Start Time: {incident_data.get('start_ts_utc', 'N/A')}
Last Update: {incident_data.get('last_update_ts_utc', 'N/A')}

SUMMARY:
{incident_data.get('summary', 'No summary available')}

"""
        
        if alerts:
            content += "\nRELATED ALERTS:\n"
            for alert in alerts[:10]:  # Show only first 10 alerts
                content += f"- [{alert.get('severity', 'N/A')}] {alert.get('alert_type', 'N/A')}: {alert.get('description', '')[:100]}\n"
        
        if ai_summary:
            content += f"\nAI ANALYSIS:\n"
            content += f"Anomaly Score: {ai_summary.get('anomaly_score', 'N/A')}\n"
            content += f"Is Anomaly: {'Yes' if ai_summary.get('is_anomaly') else 'No'}\n"
            content += f"Threshold: {ai_summary.get('threshold', 'N/A')}\n"
        
        content += f"""

GENERATED BY:
Cybersecurity SOC Dashboard - Phase 4 Operational Response
Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"reports/incident_{incident_data.get('id', 'test')}_{timestamp}.pdf"
        
        return self.generate(content, filename)