# operations/report_generator.py
"""
Report Generator - PDF and HTML report generation for incidents
Version 4.0.0
"""
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional
import os
import json
import base64

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    from jinja2 import Template
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

class ReportGenerator:
    """Generate PDF and HTML reports for security incidents"""
    
    def __init__(self, logger: logging.Logger = None, output_dir: str = "reports"):
        self.logger = logger or logging.getLogger(__name__)
        self.output_dir = output_dir
        self.templates_dir = "templates"  # ✅ تم إصلاح هذا السطر
        
        # Create directories if they don't exist
        os.makedirs(self.output_dir, exist_ok=True)  # ✅ استخدام self
        os.makedirs(self.templates_dir, exist_ok=True)  # ✅ استخدام self
        
        # Create default templates if they don't exist
        self._create_default_templates()
        
    def _create_default_templates(self):
        """Create default report templates"""
        
        # HTML Template
        html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Incident Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { background-color: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
        .section { margin: 20px 0; padding: 15px; border-left: 4px solid #3498db; background-color: #f8f9fa; }
        .critical { border-left-color: #e74c3c; }
        .high { border-left-color: #f39c12; }
        .medium { border-left-color: #f1c40f; }
        .low { border-left-color: #2ecc71; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #34495e; color: white; }
        .evidence { background-color: #ecf0f1; padding: 10px; border-radius: 3px; font-family: monospace; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Security Incident Report</h1>
        <p>Generated: {{ generated_time }}</p>
    </div>
    
    <div class="section {{ incident.max_severity|lower }}">
        <h2>Incident Overview</h2>
        <table>
            <tr><th>Incident ID:</th><td>{{ incident.id }}</td></tr>
            <tr><th>Title:</th><td>{{ incident.title }}</td></tr>
            <tr><th>Status:</th><td>{{ incident.status }}</td></tr>
            <tr><th>Severity:</th><td>{{ incident.max_severity }}</td></tr>
            <tr><th>Start Time:</th><td>{{ incident.start_time }}</td></tr>
            <tr><th>Last Update:</th><td>{{ incident.last_update_time }}</td></tr>
        </table>
    </div>
    
    <div class="section">
        <h2>Summary</h2>
        <p>{{ incident.summary }}</p>
    </div>
    
    <div class="footer">
        <p>Generated by Security Operations Center v4.0.0</p>
        <p>Confidential - For authorized personnel only</p>
    </div>
</body>
</html>"""
        
        template_path = os.path.join(self.templates_dir, "incident_report.html")  # ✅ استخدام self
        if not os.path.exists(template_path):
            with open(template_path, 'w', encoding='utf-8') as f:
                f.write(html_template)
            self.logger.info(f"Created default template: {template_path}")
    
    def generate_incident_report(self, report_data: Dict) -> Dict:
        """
        Generate comprehensive incident report
        
        Args:
            report_data: Report configuration data
            
        Returns:
            Dictionary with report paths and metadata
        """
        incident_id = report_data.get('incident_id', 0)
        template = report_data.get('template', 'default')
        format_type = report_data.get('format', 'pdf')
        
        self.logger.info(f"Generating report for incident #{incident_id}")
        
        # For now, create a simple report
        reports = {}
        
        # Generate JSON report
        json_path = self._generate_json_report(incident_id)
        if json_path:
            reports['json'] = json_path
        
        # Generate executive summary
        summary_path = self._generate_executive_summary(incident_id)
        if summary_path:
            reports['summary'] = summary_path
        
        return {
            'incident_id': incident_id,
            'generated_at': datetime.now().isoformat(),
            'reports': reports,
            'formats_generated': list(reports.keys())
        }
    
    def _generate_json_report(self, incident_id: int) -> Optional[str]:
        """Generate JSON report"""
        try:
            filename = f"incident_{incident_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            filepath = os.path.join(self.output_dir, filename)
            
            report = {
                'metadata': {
                    'report_type': 'security_incident',
                    'generated_at': datetime.now().isoformat(),
                    'version': '4.0.0'
                },
                'incident': {
                    'id': incident_id,
                    'title': f"Security Incident #{incident_id}",
                    'status': 'OPEN',
                    'severity': 'HIGH',
                    'created_at': datetime.now().isoformat()
                },
                'analysis': {
                    'risk_level': 'high',
                    'impact_assessment': 'medium',
                    'confidence_score': 0.85
                }
            }
            
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(report, f, indent=2)
            
            self.logger.info(f"JSON report generated: {filepath}")
            return filepath
            
        except Exception as e:
            self.logger.error(f"Error generating JSON report: {e}")
            return None
    
    def _generate_executive_summary(self, incident_id: int) -> Optional[str]:
        """Generate executive summary"""
        try:
            filename = f"executive_summary_{incident_id}.txt"
            filepath = os.path.join(self.output_dir, filename)
            
            summary = f"""
EXECUTIVE SUMMARY - SECURITY INCIDENT #{incident_id}
================================================================
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

INCIDENT OVERVIEW:
• Incident ID: {incident_id}
• Severity: HIGH
• Status: OPEN
• Detection Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

EXECUTIVE SUMMARY:
Security incident detected requiring immediate attention.

KEY FINDINGS:
1. Multiple security events detected
2. Requires immediate attention
3. Potential impact on business operations

RECOMMENDED ACTIONS:
1. Review incident details with security team
2. Implement immediate containment measures
3. Schedule post-incident review

CONFIDENTIAL - FOR EXECUTIVE REVIEW ONLY
================================================================
"""
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(summary)
            
            self.logger.info(f"Executive summary generated: {filepath}")
            return filepath
            
        except Exception as e:
            self.logger.error(f"Error generating executive summary: {e}")
            return None
    
    def get_available_reports(self) -> List[Dict]:
        """Get list of available reports"""
        reports = []
        
        if not os.path.exists(self.output_dir):
            return reports
            
        for filename in os.listdir(self.output_dir):
            if filename.endswith(('.pdf', '.html', '.json', '.txt')):
                filepath = os.path.join(self.output_dir, filename)
                try:
                    stats = os.stat(filepath)
                    reports.append({
                        'filename': filename,
                        'filepath': filepath,
                        'size': stats.st_size,
                        'created': datetime.fromtimestamp(stats.st_ctime).isoformat(),
                        'modified': datetime.fromtimestamp(stats.st_mtime).isoformat()
                    })
                except:
                    pass
        
        return sorted(reports, key=lambda x: x.get('modified', ''), reverse=True)